# Main configuration file

batch_size: 16  # size of batch for train data loader
no_of_classes: 16 # number of classes in multiclass classification
local:
  epoch: 50 # epochs for local learning pipeline
central:
  epoch: 50 # epochs for central learning pipeline
use_standard_dataset: false # use data from standard dataset
sd_iter: 5  # the number of iteration the experiment is repeated to calculate mean and standard deviation.


# The following are constant used for name new column introduced in dataframe
background_image_class_name: Background Image # key for relabeling background image
dataset_feature_name: source  # name of new column created to save dataset name
image_feature_name: image # name of ne column created to save image data
image_index_feature: imageIndex #name of column used to save image index
target_feature_name: errorClassCombined #name of target column
target_feature_number: classNumber  #name of target column created for binary classification

# details regarding binary classification
classification_type: binary #binary, multiclass #decribes the type of classification done
binary:
  activation: sigmoid # activation function used
  loss: binary_crossentropy # loss function used
positive_classes: -good #positive class when relabelling binary classification

#details regarding multiclass classification
multi_class:
  activation: softmax # activation function used
  loss: categorical_crossentropy  # loss function used


lr: 0.02  # learning rate for local and central learning

mu: 0.01  #not used
rho: 0.9  # rho value for federated learning
weight_decay: 0.001 # weight decay for federated learning if used

#details about metrics used
metrics:
  beta: 1 # beta value for fscore
  name: FBetaScore  # name of metrics used
  threshold: 0.5  #confidence value
  min_threshold: 0.01 # maximum allowable FPR

model: resnet # model used for training
optimizer: SGD  # optimizer used for training local, central, federated averaging and fedprox


device: cpu  #cuda or cpu
separation_type: random # split data for each client ::: random, feature
no_of_local_machines: 10  # number of client in local and federated learning
shuffle_train: false  #shuffle train dataloader
shuffle_val: false  # shuffle validation dataloader
random_oversampling: true # true for randomoversampling
weighted_sampling: false  # true for weighted oversampling, only one of weighted or random sampling should be set as true at a time
logging: true # true when results need to be saved



plot:
  plot_stat_data_loader: true #true for plotting label distribution of data loader

#constants
sampling_type: random
sampling_type_weighted: weighted
class_names_dict:
  0: Pin fehlt
  1: Pseudofehler
  2: THT Bauteil Montage falsch
  3: THT Bauteil falsch
  4: THT Bauteil fehlt
  5: THT Bauteil liegt nicht auf
  6: THT Bauteil mechan beschaedigt
  7: THT Bauteil verpolt
  8: THT Bauteil versetzt
  9: THT Loetbruecke
  10: THT Loetdurchstieg mangelhaft
  11: THT Loetst.Form mangelhaft
  12: THT Loetstelle offen
  13: THT Lotkugeln
  14: Background Image
  15: good
class_number_dict:
  Background Image: 14
  Pin fehlt: 0
  Pseudofehler: 1
  THT Bauteil Montage falsch: 2
  THT Bauteil falsch: 3
  THT Bauteil fehlt: 4
  THT Bauteil liegt nicht auf: 5
  THT Bauteil mechan beschaedigt: 6
  THT Bauteil verpolt: 7
  THT Bauteil versetzt: 8
  THT Loetbruecke: 9
  THT Loetdurchstieg mangelhaft: 10
  THT Loetst.Form mangelhaft: 11
  THT Loetstelle offen: 12
  THT Lotkugeln: 13
  good: 15


Number_of_classes: 16 #number of classes for multiclass classification

#path of different configuration files
data_augmentation: #path of augmentation configuration files
  C:/Users/yadhu/Desktop/thesis_code/image-classification-master/config_directory/augmentation_configuration.yaml
federated_learning: #path of federated learning configuration files
  C:/Users/yadhu/Desktop/thesis_code/image-classification-master/config_directory/federatedlearning_configuration.yaml

fetch_image: C:/Users/yadhu/Desktop/thesis_code/image-classification-master/save_dataframe/ #path of dataframe save and fetch location

image: #path of image configuration files
  C:/Users/yadhu/Desktop/thesis_code/image-classification-master/config_directory/image_configuration.yaml
local_learning: #path of learning configuration files
  C:/Users/yadhu/Desktop/thesis_code/image-classification-master/config_directory/learning_configuration.yaml
splitting: #path of splitting configuration files
  C:/Users/yadhu/Desktop/thesis_code/image-classification-master/config_directory/splitting_configuration.yaml

paths:
  logging_path: C:/Users/yadhu/Desktop/thesis_code/Logs #path for saving log files