augment: True

resize:
  on: true
  #size: 224  #size for resnet
  size: 256   #size for VGG
crop_center:
  on: false  #True for VGG
  size: 224

rotation:
  on: true
  max_degrees: 180
  min_degrees: 0

normalize:
  on: true
  mean: [0.485, 0.456, 0.406]
  standard_deviation: [0.229, 0.224, 0.225]

flipping:
  on: true
  probability: 0.3
mirroring:
  on: True
  probability: 0.3